const btc = "BTC",
  eth = "ETH",
  btcSymbol = "BTCUSD",
  ethSymbol = "ETHUSD",
  ethWindow = 20,
  btcWindow = 200,
  strikeGap = 2,
  maker = "Maker",
  taker = "Taker",
  limit = "Limit",
  market = "Market",
  option = "Option",
  history = "History",
  track = "Track",
  alert = "Alert",
  alarm = "Alarm",
  volume = "Volume",
  oi = "Oi",
  buy = "Buy",
  sell = "Sell",
  delta = "Delta",
  candle = "Candle",
  reverse = "Reverse",
  update = "update",
  adjust = "Adjust",
  model = "Model",
  log = "Log",
  database = "Database",
  test = "Test",
  active = "Active",
  inactive = "Inactive",
  hold = "Hold",
  none = "None",
  top = "Top",
  addon = "Addon",
  call = "Call",
  put = "Put",
  C = "C",
  P = "P",
  horizontal = "Horizontal",
  vertical = "Vertical",
  horizontalHalf = "HorizontalHalf",
  verticalHalf = "VerticalHalf",
  horizontalFull = "HorizontalFull",
  verticalFull = "VerticalFull",
  mobile = "Mobile",
  tablet = "Tablet",
  main = "Main",
  support = "Support",
  mainAddon = "MainAddon",
  supportAddon = "SupportAddon",
  success = "Success",
  error = "Error",
  info = "Information",
  tickerChannel = "v2/ticker",
  candlestick_ = "candlestick_",
  usd = "USD",
  inr = "INR",
  usdConv = 90,
  btcLotsize = 0.001,
  ethLotsize = 0.01,
  start = "Start",
  stop = "Stop",
  para = "Para",
  trn = "Trn",
  buyDelta = "BuyDelta",
  position = "Position",
  marketOrder = "market",
  limitOrder = "limit",
  buyOrder = "buy",
  sellOrder = "sell",
  message = "Message",
  backtest = "Backtest",
  chart = "Chart",
  data = "Data",
  fixUp = "Fix Up",
  fixDown = "Fix Dn",
  trailUp = "Trail Up",
  trailDown = "Trail Dn",
  greenWindow = "YellowGreen",
  orangeWindow = "SandyBrown",
  yellowWindow = "#FEF9C2",
  blueWindow = "#a2dfecff",
  greyWindow = "#a9a9a9",
  invisibleColor = "#F3F6F4",
  up = "Up",
  down = "Down",
  average = "Average",
  percentage = "Percentage",
  P1 = "P1",
  P2 = "P2",
  P3 = "P3",
  notify_error = "rotating_light",
  notify_warning = "warning",
  notify_success = "zap", // recycle
  notify_buy = "shopping_cart",
  notify_sell = "truck",
  notify_support = "balance_scale",
  notify_reverse = "paperclips",
  notify_alarm = "alarm_clock",
  notify_alert = "bell",
  notify_target = "alarm_clock",
  notify_loss = "name_badge",
  notify_low = "3",
  notify_medium = "4",
  notify_high = "5",
  timeframe = {
    "3m": "3m",
    "5m": "5m",
    "15m": "15m",
    "30m": "30m",
    "1h": "1h",
    "2h": "2h",
    "4h": "4h",
    "6h": "6h",
  },
  aMonth = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  large = "Large",
  medium = "Medium",
  small = "Small",
  fixed = "Fixed",
  trail = "Trail",
  positive = "Positive",
  negative = "Negative",
  both = "Both",
  smallFactor = 15,
  mediumFactor = 20,
  largeFactor = 25,
  minToMili = 60000,
  hourToMili = 3600000,
  busyDelay = 2000,
  logPath = "./src/log/";

const defaultPara = {
  initPara: model,
  switch: test,
  interval: "15m",
  scale: medium,
  strikeGap: 3,
  barType: option,
};

const recordSchema = {
  mode: String,
  timestamp: Number,
  index: String,
  type: String,
  call: String,
  put: String,
  amount: Number,
  pnl: Number,
  support: Number,
  supportPer: Number,
  addonCount: Number,
  addonPer: Number,
  slippage: Number,
  slippagePer: Number,
  reverse: Number,
};

const historySchema = {
  symbol: String,
  type: String,
  category: String,
  icon: String,
  parent: Number,
  buyTime: Number,
  buyTimeText: String,
  sellTime: Number,
  sellTimeText: String,
  buy: Number,
  ltp: Number,
  per: Number,
  buySlp: Number,
  sellSlp: Number,
};

module.exports = {
  btc,
  eth,
  btcSymbol,
  ethSymbol,
  ethWindow,
  btcWindow,
  strikeGap,
  maker,
  taker,
  limit,
  market,
  option,
  history,
  track,
  alert,
  alarm,
  volume,
  oi,
  buy,
  sell,
  delta,
  candle,
  reverse,
  update,
  adjust,
  test,
  model,
  log,
  database,
  active,
  inactive,
  hold,
  none,
  top,
  addon,
  call,
  put,
  C,
  P,
  horizontal,
  vertical,
  horizontalHalf,
  verticalHalf,
  horizontalFull,
  verticalFull,
  mobile,
  tablet,
  main,
  support,
  mainAddon,
  supportAddon,
  success,
  error,
  info,
  tickerChannel,
  candlestick_,
  usd,
  inr,
  usdConv,
  btcLotsize,
  ethLotsize,
  start,
  stop,
  para,
  trn,
  buyDelta,
  position,
  marketOrder,
  limitOrder,
  buyOrder,
  sellOrder,
  message,
  backtest,
  chart,
  data,
  fixUp,
  fixDown,
  trailUp,
  trailDown,
  greenWindow,
  orangeWindow,
  yellowWindow,
  blueWindow,
  greyWindow,
  invisibleColor,
  up,
  down,
  average,
  percentage,
  P1,
  P2,
  P3,
  notify_error,
  notify_warning,
  notify_success,
  notify_buy,
  notify_sell,
  notify_support,
  notify_reverse,
  notify_alarm,
  notify_alert,
  notify_target,
  notify_loss,
  notify_low,
  notify_medium,
  notify_high,
  timeframe,
  aMonth,
  large,
  medium,
  small,
  fixed,
  trail,
  positive,
  negative,
  both,
  smallFactor,
  mediumFactor,
  largeFactor,
  minToMili,
  hourToMili,
  busyDelay,
  logPath,
  defaultPara,
  recordSchema,
  historySchema,
};
